deployments:
- name: taxi-xgb-model
  entrypoint: week3/orchestrate_hw.py:main_flow
  work_pool:
    name: dtc-course-pool

- name: send-noti-email
  entrypoint: week3/send_email.py:send_email
  work_pool:
    name: dtc-course-pool


